name = "imarika-api"
main = "src/worker.js"
compatibility_date = "2024-10-01"

[[d1_databases]]
binding = "DB"                          # <-- matches your snippet
database_name = "imarika"
database_id = "27e54d46-8ff9-4791-8396-3feac7bf6ff4"

# serve the API at https://www.imarika.net/api/*
routes = [
  { pattern = "www.imarika.net/api/*", zone_name = "imarika.net" }
]

[dev]
port = 8787
